/* VF_V2_EXECUTION_20260819 · public homepage runtime */
(function(){
'use strict';
var shell=null,proofIndex=0,proofImages=[];
var programs=[
{id:'foundation-4week',name:'FOUNDATION',outcome:'Build gym confidence and movement fundamentals.',level:'Beginner',price:15,duration:'4 weeks'},
{id:'iron-beast-8week',name:'IRON BEAST',outcome:'Build strength with progressive compound training.',level:'Powerlifting',price:35,duration:'8 weeks'},
{id:'home-30day',name:'HOME 45',outcome:'Get consistent at home with minimal equipment.',level:'Home',price:25,duration:'45 days'},
{id:'booty-camp-8week',name:'BOOTY CAMP',outcome:'Build glute strength, shape and lower-body confidence.',level:'Glutes',price:30,duration:'8 weeks'},
{id:'sixpack-8week',name:'SHREDDED SIX',outcome:'Cut body fat while training for visible definition.',level:'Men',price:30,duration:'8 weeks'},
{id:'hourglass-8week',name:'HOURGLASS',outcome:'Shape, condition and progress through structured training.',level:'Women',price:35,duration:'8 weeks'},
{id:'mass-monster-8week',name:'MASS MONSTER',outcome:'Add size and strength with progressive overload.',level:'Muscle',price:35,duration:'8 weeks'}
];
var coaches=[
{slug:'darvano-andrews',name:'Darvano Andrews',initials:'DA',role:'Founder & Lead Coach',specialty:'Body Recomposition · Glute Specialist · Muscle Gain',transformations:'500+'},
{slug:'lanardo-mackey',name:'Lanardo Mackey',initials:'LM',role:'VFITNESS Coach',specialty:'Weight Loss · Body Recomposition · Group Training',transformations:'180+'},
{slug:'chavese-moss',name:'Chavese Moss',initials:'CM',role:'VFITNESS Coach',specialty:'Weight Loss · Body Recomposition · Athletic Coaching',transformations:'220+'},
{slug:'kevin-mackey',name:'Kevin Mackey',initials:'KM',role:'VFITNESS Coach',specialty:'Body Recomposition · Group Training · Accountability',transformations:'120+'}
];
var faqs=[
['Where does VFitness train in Nassau?','In-person coaching is available at Empire Fitness, Fanta C, and the Royal Bahamas Police College. Your training location is confirmed during onboarding.'],
['Do I need a gym membership?','Access requirements depend on the location and session arrangement. Your coach will confirm exactly what applies before your first session.'],
['Which coach will I train with?','We match you by goal, schedule, location, and coaching fit. You can also request a coach and we will confirm availability.'],
["I've never lifted before. Can I still join?",'Yes. Your assessment establishes your starting point and your program progresses from your current experience level.'],
['What happens if I travel or miss a session?','Your program and progress remain in your account. For travel or schedule changes, contact your coach so the next training step can be adjusted.'],
['How do packages and payments work?','In-person coaching is sold by session package. Online programs show their price before checkout, and membership tiers show exactly what is included.'],
['Can I switch trainers?','Yes. Contact VFitness and we will review the change based on coach availability, schedule, and location.'],
["Can I train with VFitness if I don't live in The Bahamas?",'Yes. Online programs and remote coaching are designed for clients training from anywhere.']
];
function esc(s){return String(s==null?'':s).replace(/[&<>"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c];});}
function cleanPath(){return (location.pathname||'/').replace(/\/+$/,'')||'/';}
function isHome(){var p=cleanPath();return p==='/'||p==='/home';}
function txt(el){return ((el&&el.textContent)||'').replace(/\s+/g,' ').trim();}
function money(v){return '$'+Number(v||0).toFixed(0);}
function proofMedia(){var seen={},out=[];document.querySelectorAll('#root img').forEach(function(img){var src=img.currentSrc||img.src||'';if(!src||seen[src]||/icon|logo|avatar|favicon|program-|scene-/i.test(src))return;var p=img.closest('section,article,div');var ctx=((img.alt||'')+' '+txt(p).slice(0,900)).toLowerCase();if(!/transform|before|after|client result|progress|testimonial|success stor/.test(ctx))return;seen[src]=1;out.push({src:src,alt:img.alt||'VFitness client transformation'});});return out.slice(0,3);}
function bolt(){return '<span class="vf-v2-bolt" aria-hidden="true"><svg width="15" height="18" viewBox="0 0 20 24"><path d="M11.8 1 3 13h6l-.8 10L17 10h-6l.8-9Z" fill="currentColor"/></svg></span>';}
function nav(){return '<header class="vf-v2-nav"><div class="vf-v2-wrap vf-v2-navin"><a class="vf-v2-logo" href="/">'+bolt()+'<span>VFITNESS</span></a><nav class="vf-v2-navlinks" aria-label="Primary"><a href="/programs">Programs</a><a href="/trainers">Trainers</a><a href="/results">Results</a><a href="/pricing">Pricing</a><a href="/contact">Contact</a></nav><a class="vf-v2-account" href="/dashboard" aria-label="Account">◎</a><button class="vf-v2-menu" type="button" aria-label="Open menu" aria-expanded="false">☰</button></div><nav class="vf-v2-mobilemenu" aria-label="Mobile"><a href="/programs">Programs</a><a href="/trainers">Trainers</a><a href="/results">Results</a><a href="/pricing">Pricing</a><a href="/contact">Contact</a><a href="/dashboard">Account</a></nav></header>';}
function hero(){return '<section class="vf-v2-hero"><div class="vf-v2-wrap vf-v2-heroin"><div class="vf-v2-herobadge vf-v2-eyebrow">PERSONAL TRAINER IN NASSAU, BAHAMAS</div><h1 class="vf-v2-h1"><span>Built Different.</span><span>Trained Different.</span><span>Results Tracked.</span></h1><p class="vf-v2-copy">Structured training, nutrition, accountability and progress tracking — in Nassau or online.</p><div class="vf-v2-heroactions"><a class="vf-v2-primary" href="/start">Start Your Transformation</a><a class="vf-v2-secondary" href="/programs">Browse Programs</a></div><div class="vf-v2-proofstrip">500+ TRANSFORMATIONS · 4 COACHES · 3 NASSAU GYMS</div></div></section>';}
function proof(){return '<section class="vf-v2-proofbar" aria-label="VFitness proof"><div class="vf-v2-proofstat"><strong>500+</strong><span>Transformations</span></div><div class="vf-v2-proofstat"><strong>4</strong><span>Coaches</span></div><div class="vf-v2-proofstat"><strong>3</strong><span>Nassau gyms</span></div><div class="vf-v2-proofstat"><strong>18</strong><span>Sessions per phase</span></div></section>';}
function system(){var s=[['01','Assess','Fitness assessment establishes the starting point.'],['02','Program','Build an 18-session phase around the goal.'],['03','Train','Every session is coached and logged.'],['04','Track','Weekly check-ins and progress decide what changes next.']];return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">THE SYSTEM</span><h2 class="vf-v2-h2">A method you can explain in one minute.</h2><p class="vf-v2-copy">VFitness turns coaching into a repeatable process instead of a collection of random workouts.</p></div><div class="vf-v2-system">'+s.map(function(x){return '<div class="vf-v2-step"><div class="vf-v2-num">'+x[0]+'</div><div><h3 class="vf-v2-h3">'+x[1]+'</h3><p>'+x[2]+'</p></div></div>';}).join('')+'</div></div></section>';}
function paths(){return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">CHOOSE YOUR PATH</span><h2 class="vf-v2-h2">Train here or train anywhere.</h2></div><div class="vf-v2-grid2"><article class="vf-v2-card vf-v2-path"><div><h3 class="vf-v2-h3">Train in Nassau</h3><p class="vf-v2-copy" style="margin-top:10px">Three gyms, four coaches, 1-on-1 and small-group coaching with sessions tracked inside VFitness.</p></div><p class="vf-v2-caption">Empire Fitness · Fanta C · Royal Bahamas Police College</p><a class="vf-v2-linkbtn" href="/pricing">See in-person options</a></article><article class="vf-v2-card vf-v2-path"><div><h3 class="vf-v2-h3">Train Online</h3><p class="vf-v2-copy" style="margin-top:10px">Structured programs and remote coaching for clients who want the VFitness system from anywhere.</p></div><p class="vf-v2-caption">Programs · Progress tracking · Remote accountability</p><a class="vf-v2-linkbtn" href="/programs">Browse online programs</a></article></div></div></section>';}
function programCards(){return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">PROGRAMS</span><h2 class="vf-v2-h2">Choose the outcome. Follow the structure.</h2></div><div class="vf-v2-programgrid">'+programs.map(function(p){return '<article class="vf-v2-card vf-v2-program"><div class="vf-v2-programmeta"><span class="vf-v2-pill">'+esc(p.level)+'</span><span class="vf-v2-pill">'+esc(p.duration)+'</span></div><h3 class="vf-v2-h3">'+esc(p.name)+'</h3><p class="vf-v2-caption">'+esc(p.outcome)+'</p><div class="vf-v2-price">'+money(p.price)+'</div><div class="vf-v2-included">or included with Programming — $59/mo.</div><a class="vf-v2-linkbtn" href="/programs/'+encodeURIComponent(p.id)+'">View program</a></article>';}).join('')+'</div></div></section>';}
function coachCards(){return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">COACHES</span><h2 class="vf-v2-h2">Four coaches. One system.</h2></div><div class="vf-v2-coachgrid">'+coaches.map(function(c){return '<a class="vf-v2-card vf-v2-coach" href="/trainers/'+c.slug+'"><div class="vf-v2-avatar">'+c.initials+'</div><div><h3 class="vf-v2-h3">'+esc(c.name)+'</h3><div class="vf-v2-caption" style="margin-top:4px">'+esc(c.role)+'</div></div><div class="vf-v2-transform">'+esc(c.transformations)+' transformations</div><div class="vf-v2-coachspec">'+esc(c.specialty)+'</div></a>';}).join('')+'</div></div></section>';}
function results(){if(!proofImages.length)return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">RESULTS</span><h2 class="vf-v2-h2">Real clients only.</h2></div><div class="vf-v2-emptyproof">Transformation media is intentionally hidden until a real, consented client image is available.</div></div></section>';return '<section class="vf-v2-section vf-v2-results"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">RESULTS</span><h2 class="vf-v2-h2">The system has to show up in the result.</h2></div><div class="vf-v2-resultsview"><div class="vf-v2-resulttrack">'+proofImages.map(function(x){return '<figure class="vf-v2-resultslide"><img src="'+esc(x.src)+'" alt="'+esc(x.alt)+'" loading="lazy" decoding="async"></figure>';}).join('')+'</div></div><div class="vf-v2-resultmeta"><span class="vf-v2-caption vf-v2-resultcount">01 / '+String(proofImages.length).padStart(2,'0')+'</span><div class="vf-v2-resultarrows"><button class="vf-v2-arrow vf-v2-resultprev" type="button">←</button><button class="vf-v2-arrow vf-v2-resultnext" type="button">→</button></div></div></div></section>';}
function pricing(){var tiers=[{n:'Tracking',p:19,items:['Progress dashboard','Workout and session history','Account tracking']},{n:'Programming',p:59,rec:true,items:['Structured program access','Training progression','Check-ins and progress tools']},{n:'Coaching',p:99,items:['Programming membership','Coach review and accountability','Higher-touch support']}];return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">PRICING</span><h2 class="vf-v2-h2">Know the cost before you commit.</h2></div><div class="vf-v2-tiergrid">'+tiers.map(function(t){return '<article class="vf-v2-card vf-v2-tier '+(t.rec?'recommended':'')+'">'+(t.rec?'<div class="vf-v2-rec">Recommended</div>':'')+'<h3 class="vf-v2-h3">'+t.n+'</h3><div class="vf-v2-price">$'+t.p+'<span class="vf-v2-caption"> / month</span></div><ul class="vf-v2-list">'+t.items.map(function(i){return '<li>'+i+'</li>';}).join('')+'</ul><a class="vf-v2-linkbtn" href="/start">Get started</a></article>';}).join('')+'</div><div style="margin-top:38px"><h3 class="vf-v2-h3">In-person packages</h3><div class="vf-v2-packagegrid"><div class="vf-v2-package"><strong>1-on-1 Personal Training</strong><div class="vf-v2-caption">1 · 4 · 6 · 8 · 12 sessions</div><div class="vf-v2-packageprices"><span>$30</span><span>$120</span><span>$180</span><span>$221</span><span>$294</span></div></div><div class="vf-v2-package"><strong>Semi-Private Training</strong><div class="vf-v2-caption">1 · 4 · 6 · 8 · 12 sessions</div><div class="vf-v2-packageprices"><span>$22</span><span>$87</span><span>$130</span><span>$173</span><span>$195</span></div></div></div><a class="vf-v2-linkbtn" style="margin-top:14px" href="/pricing">View full package details</a></div><div style="margin-top:38px"><h3 class="vf-v2-h3">Online programs</h3><p class="vf-v2-caption" style="margin-top:8px">One-time program prices range from $15–$35, or use Programming at $59/month.</p></div></div></section>';}
function faq(){return '<section class="vf-v2-section"><div class="vf-v2-wrap"><div class="vf-v2-head"><span class="vf-v2-eyebrow">FAQ</span><h2 class="vf-v2-h2">The questions people ask before starting.</h2></div><div class="vf-v2-faq">'+faqs.map(function(x){return '<details><summary>'+esc(x[0])+'</summary><p>'+esc(x[1])+'</p></details>';}).join('')+'</div><div class="vf-v2-close" style="margin-top:44px"><span class="vf-v2-eyebrow">READY WHEN YOU ARE</span><h2 class="vf-v2-h2">Start with the system. Build the result.</h2><a class="vf-v2-primary" href="/start">Start Your Transformation</a></div></div></section>';}
function bind(){var menu=shell.querySelector('.vf-v2-menu'),mobile=shell.querySelector('.vf-v2-mobilemenu');if(menu&&mobile)menu.onclick=function(){var on=mobile.classList.toggle('is-open');menu.setAttribute('aria-expanded',on?'true':'false');menu.textContent=on?'×':'☰';};var track=shell.querySelector('.vf-v2-resulttrack');if(!track)return;function go(n){proofIndex=(n+proofImages.length)%proofImages.length;track.style.transform='translate3d(-'+(proofIndex*100)+'%,0,0)';var c=shell.querySelector('.vf-v2-resultcount');if(c)c.textContent=String(proofIndex+1).padStart(2,'0')+' / '+String(proofImages.length).padStart(2,'0');}var p=shell.querySelector('.vf-v2-resultprev'),n=shell.querySelector('.vf-v2-resultnext');if(p)p.onclick=function(){go(proofIndex-1)};if(n)n.onclick=function(){go(proofIndex+1)};var sx=null;track.addEventListener('touchstart',function(e){sx=e.touches[0].clientX},{passive:true});track.addEventListener('touchend',function(e){var ex=e.changedTouches[0].clientX;if(sx!=null&&Math.abs(ex-sx)>42)go(proofIndex+(ex<sx?1:-1));sx=null},{passive:true});}
function mount(){if(!isHome())return unmount();if(shell&&shell.isConnected)return;var root=document.getElementById('root');if(!root||txt(root).length<80)return;proofImages=proofMedia();root.style.display='none';shell=document.createElement('div');shell.id='vf-v2-public-shell';shell.innerHTML=nav()+hero()+proof()+system()+paths()+programCards()+coachCards()+results()+pricing()+faq()+'<footer class="vf-v2-footer"><div class="vf-v2-wrap">VFITNESS · Nassau, Bahamas · Training, programming and progress tracking.</div></footer>';document.body.appendChild(shell);bind();}
function unmount(){if(shell&&shell.parentNode)shell.remove();shell=null;var root=document.getElementById('root');if(root)root.style.display='';}
function cleanup(){if(innerWidth<768)document.querySelectorAll('button,div,a').forEach(function(el){var r=el.getBoundingClientRect(),t=txt(el),cs=getComputedStyle(el);if((t==='>'||t==='›'||t==='❯')&&cs.position==='fixed'&&r.left<8&&r.width<72&&r.height<140)el.style.display='none';});document.querySelectorAll('body *').forEach(function(el){if(el.children.length)return;var t=txt(el);if(/\b(days|weeks)\s+weeks\b/i.test(t))el.textContent=t.replace(/\b(days|weeks)\s+weeks\b/ig,'$1');});if(/^\/trainers(?:\/|$)/.test(cleanPath())){document.querySelectorAll('div,span').forEach(function(el){var t=txt(el);if(/^(5\.0|4\.9)\s*[·•]/.test(t))el.textContent=t.replace(/^(5\.0|4\.9)\s*[·•]\s*/,'');});var slug=cleanPath().split('/')[2],c=coaches.find(function(x){return x.slug===slug});if(c){var target=Array.from(document.querySelectorAll('h2,h3,div')).find(function(el){return txt(el)===c.name});if(target)setTimeout(function(){target.scrollIntoView({behavior:'smooth',block:'center'})},100);}}}
function run(){mount();cleanup();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(run,80);setTimeout(run,500);setTimeout(run,1100)});else{setTimeout(run,40);setTimeout(run,450);setTimeout(run,1000)}
window.addEventListener('pageshow',function(){setTimeout(run,80)});window.addEventListener('popstate',function(){unmount();setTimeout(run,80)});window.addEventListener('vf:ui-rendered',function(){setTimeout(run,100)});window.addEventListener('vf:navigation',function(){unmount();setTimeout(run,100)});
})();
